// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oseowhythgbqvllwonaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZW93aHl0aGdicXZsbHdvbmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTgyNzgsImV4cCI6MjA1NzE5NDI3OH0.MubP80cszCAeIeyve_uY9zLZosck9010uhvbxBC57vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);